### ISSUE TITLE
XQuartz.app not launching when started via LaunchAgent

### ISSUE THREAD

**Issue by tgorni** [XQuartz/XQuartz#102]
Hi, XQuartz-2.8.0_rc2 stopped working on my Mac Book Pro, OS Catalina (10.15.7). Whenever I launch an app requiring Xquartz (xclock, xterm, gnuplot with x11 terminal), nothing happens. I tried to uninstall and reinstall XQuartz from scratch, but it didn't do any good. From the description, I think my issue is very similar to #96. 

I said 'it stopped working' since on a fresh installation of Catalina XQuartz seemed to work fine at first, but after I installed other tools (intel compilers, mac ports,...) the issue above appeared, I don't know whether conflicts might have occurred, in any case nothing as such has ever happened to me on my previous Yosemite installation.

**Comment by jeremyhu** [comment]
Can you backup your /opt/X11, then re-install 2.8.0_rc2, then see if that starts working?

If so, can you compare the contents of /opt/X11 and your backup to see what might be different?  Eg:

    cd /opt/X11
    find . > /tmp/files.a
    cd /opt/X11.bak
    find . > /tmp/files.b
    diff -Naurp /tmp/files.[ab]

**Comment by tgorni** [comment]
I had already uninstalled Xquartz following the instructions [here](https://www.xquartz.org/FAQs.html), I tried nonetheless to re-install 2.8.0_rc2 it and the same problem occurs. Even if I double-click on Xquartz in /Applications/Utilities the icon bounces a couple of times and then stops without opening.

**Comment by Jipingnersc** [comment]
This morning I upgraded my XQuartz. The same issue happens on my mac.

**Comment by aivils** [comment]
I tried 2.8.0_rc2. All X11 apps no longer worked. I cleaned up /opt/X11 - does not help.
I go back to 2.7.11. Nothing works.
I discover weird DISPLAY

```
$ export | grep DISPLAY
declare -x DISPLAY="/private/tmp/com.apple.launchd.EbnpOxmeWn/org.xquartz:0"
```

I set "normal" DISPLAY in the iterm.

```
export DISPLAY=":0"
```

All apps started working again including over ssh (started from that iterm).
Unfortunately, there is no idea where to change this DISPLAY for the whole system.
Never tried 2.8.0 again.

**Comment by jeremyhu** [comment]
That's not a "weird" DISPLAY.  That's the path to the DISPLAY socket for the startx LaunchAgent.

Setting it to :0 means it uses  /tmp/.X11-unix/X0, which may or may not be your server.

**Comment by jeremyhu** [comment]
@aivils You need to uninstall 2.8.0 then re-install 2.7.11, then logout and backin if you want to downgrade.

**Comment by jeremyhu** [comment]
If you open up Terminal.app and run `xterm` from there, do you see any error message?

Are you seeing this happen only after waking from sleep (cf #108)

**Comment by aivils** [comment]
I uninstall 2.8.0 single time. I re-install 2.7.11 about 3 times (with back up /opt/X11). I restarted PC about 5 times. A few times logout/login. All these actions did not change anything. xterm starts without errors but the window does not appear. The same is with Terminal.app, if you run xterm then there is no error message but the window does not appear.

If I run xterm from Xquartz (Applications -> Terminal), a window appears and the DISPLAY value is ":0".

**Comment by Jipingnersc** [comment]
I uninstall 2.8.0 and reinstall the previous version 2.7.11. The xterm works well as before on mac.

**Comment by aivils** [comment]
In the syslog I see the following entries when I try to run xterm. Maybe it will help.

```
$ grep xquartz system.log
Mar  6 18:04:03 Aivilss-MacBook-Pro-2 org.macosforge.xquartz.startx[717]: /opt/X11/bin/xinit: connection to X server lost
Mar  6 18:04:03 Aivilss-MacBook-Pro-2 org.macosforge.xquartz.startx[717]:
Mar  6 18:04:04 Aivilss-MacBook-Pro-2 org.macosforge.xquartz.startx[717]: waiting for X server to shut down
Mar  6 18:04:09 Aivilss-MacBook-Pro-2 org.macosforge.xquartz.startx[717]: waiting for X server to shut down xauth: (argv):1:  bad display name "Aivilss-MacBook-Pro-2.local:0" in "remove" command
Mar  6 18:04:09 Aivilss-MacBook-Pro-2 org.macosforge.xquartz.startx[717]: waiting for X server to shut down
Mar  6 18:04:10 Aivilss-MacBook-Pro-2 com.apple.xpc.launchd[1] (org.macosforge.xquartz.privileged_startx[3642]): Endpoint has been activated through legacy launch(3) APIs. Please switch to XPC or bootstrap_check_in(): org.macosforge.xquartz.privileged_startx
Mar  6 18:04:10 Aivilss-MacBook-Pro-2 org.macosforge.xquartz.privileged_startx[3642]: /opt/X11/bin/font_cache: line 92: /System/Library/Fonts/fonts.list: Operation not permitted
Mar  6 18:04:10 Aivilss-MacBook-Pro-2 org.macosforge.xquartz.privileged_startx[3642]: /opt/X11/bin/font_cache: line 92: /System/Library/Fonts/Supplemental/fonts.list: Operation not permitted
Mar  6 18:04:10 Aivilss-MacBook-Pro-2 org.macosforge.xquartz.startx[3633]: expr: syntax error
Mar  6 18:04:10 Aivilss-MacBook-Pro-2 org.macosforge.xquartz.startx[3633]: xauth:  file /Users/aivilsstoss/.serverauth.3634 does not exist
Mar  6 18:04:10 Aivilss-MacBook-Pro-2 org.macosforge.xquartz.privileged_startx[3642]: /System/Library/Fonts/fonts.scale: fopen(w): Operation not permitted
Mar  6 18:04:10 Aivilss-MacBook-Pro-2 org.macosforge.xquartz.privileged_startx[3642]: /System/Library/Fonts/fonts.dir: fopen(w): Operation not permitted
Mar  6 18:04:10 Aivilss-MacBook-Pro-2 org.macosforge.xquartz.privileged_startx[3642]: /System/Library/Fonts/Supplemental/fonts.scale: fopen(w): Operation not permitted
Mar  6 18:04:10 Aivilss-MacBook-Pro-2 org.macosforge.xquartz.privileged_startx[3642]: /System/Library/Fonts/Supplemental/fonts.dir: fopen(w): Operation not permitted
Mar  6 18:04:15 Aivilss-MacBook-Pro-2 org.macosforge.xquartz.startx[3633]: xauth: (argv):1:  bad display name "Aivilss-MacBook-Pro-2.local:0" in "list" command
Mar  6 18:04:20 Aivilss-MacBook-Pro-2 org.macosforge.xquartz.startx[3633]: xauth: (stdin):1:  bad display name "Aivilss-MacBook-Pro-2.local:0" in "add" command
Mar  6 18:04:20 Aivilss-MacBook-Pro-2 org.macosforge.xquartz.X11.stub[3780]: launchd check-in: No known sockets found to answer requests on! "org.macosforge.xquartz:0" and ":0" failed.
Mar  6 18:04:20 Aivilss-MacBook-Pro-2 org.macosforge.xquartz.X11.stub[3780]: Xquartz: Unable to locate waiting server: org.macosforge.xquartz.X11
Mar  6 18:04:20 Aivilss-MacBook-Pro-2 org.macosforge.xquartz.X11.stub[3781]: Xquartz: Starting X server: /Applications/Utilities/XQuartz.app/Contents/MacOS/X11 --listenonly
Mar  6 18:04:22 Aivilss-MacBook-Pro-2 org.macosforge.xquartz.startx[3633]: /opt/X11/bin/xinit: XFree86_VT property unexpectedly has 0 items instead of 1
Mar  6 18:04:26 Aivilss-MacBook-Pro-2 org.macosforge.xquartz.startx[3633]: /opt/X11/bin/xinit: connection to X server lost
Mar  6 18:04:26 Aivilss-MacBook-Pro-2 org.macosforge.xquartz.startx[3633]:
Mar  6 18:04:27 Aivilss-MacBook-Pro-2 org.macosforge.xquartz.startx[3633]: waiting for X server to shut down
Mar  6 18:04:42 Aivilss-MacBook-Pro-2 com.apple.xpc.launchd[1] (org.macosforge.xquartz.startx): The ServiceIPC key is no longer respected. Please remove it.
Mar  6 18:04:42 Aivilss-MacBook-Pro-2 com.apple.xpc.launchd[1] (org.xquartz.startx): The ServiceIPC key is no longer respected. Please remove it.
Mar  6 18:05:37 Aivilss-MacBook-Pro-2 com.apple.xpc.launchd[1] (org.macosforge.xquartz.privileged_startx[4198]): Endpoint has been activated through legacy launch(3) APIs. Please switch to XPC or bootstrap_check_in(): org.macosforge.xquartz.privileged_startx
Mar  6 18:05:37 Aivilss-MacBook-Pro-2 org.macosforge.xquartz.privileged_startx[4198]: /opt/X11/bin/font_cache: line 92: /System/Library/Fonts/fonts.list: Operation not permitted
Mar  6 18:05:37 Aivilss-MacBook-Pro-2 org.macosforge.xquartz.privileged_startx[4198]: /opt/X11/bin/font_cache: line 92: /System/Library/Fonts/Supplemental/fonts.list: Operation not permitted
Mar  6 18:05:37 Aivilss-MacBook-Pro-2 org.macosforge.xquartz.startx[4189]: expr: syntax error
Mar  6 18:05:37 Aivilss-MacBook-Pro-2 org.macosforge.xquartz.startx[4189]: xauth:  file /Users/aivilsstoss/.serverauth.4190 does not exist
Mar  6 18:05:37 Aivilss-MacBook-Pro-2 org.macosforge.xquartz.privileged_startx[4198]: /System/Library/Fonts/fonts.scale: fopen(w): Operation not permitted
Mar  6 18:05:37 Aivilss-MacBook-Pro-2 org.macosforge.xquartz.privileged_startx[4198]: /System/Library/Fonts/fonts.dir: fopen(w): Operation not permitted
Mar  6 18:05:37 Aivilss-MacBook-Pro-2 org.macosforge.xquartz.privileged_startx[4198]: /System/Library/Fonts/Supplemental/fonts.scale: fopen(w): Operation not permitted
Mar  6 18:05:37 Aivilss-MacBook-Pro-2 org.macosforge.xquartz.privileged_startx[4198]: /System/Library/Fonts/Supplemental/fonts.dir: fopen(w): Operation not permitted
Mar  6 18:05:42 Aivilss-MacBook-Pro-2 org.macosforge.xquartz.startx[4189]: xauth: (argv):1:  bad display name "Aivilss-MacBook-Pro-2.local:0" in "list" command
Mar  6 18:05:47 Aivilss-MacBook-Pro-2 org.macosforge.xquartz.startx[4189]: xauth: (stdin):1:  bad display name "Aivilss-MacBook-Pro-2.local:0" in "add" command
Mar  6 18:05:47 Aivilss-MacBook-Pro-2 org.macosforge.xquartz.X11.stub[4340]: launchd check-in: No known sockets found to answer requests on! "org.macosforge.xquartz:0" and ":0" failed.
Mar  6 18:05:47 Aivilss-MacBook-Pro-2 org.macosforge.xquartz.X11.stub[4340]: Xquartz: Unable to locate waiting server: org.macosforge.xquartz.X11
Mar  6 18:05:47 Aivilss-MacBook-Pro-2 org.macosforge.xquartz.X11.stub[4341]: Xquartz: Starting X server: /Applications/Utilities/XQuartz.app/Contents/MacOS/X11 --listenonly
Mar  6 18:05:49 Aivilss-MacBook-Pro-2 org.macosforge.xquartz.startx[4189]: /opt/X11/bin/xinit: XFree86_VT property unexpectedly has 0 items instead of 1
```

**Comment by aivils** [comment]
Additional entries that mention DISPLAY

```
$ cat /Users/aivilsstoss/Library/Logs/X11/org.macosforge.xquartz.log
X11.app: DISPLAY ("/private/tmp/com.apple.launchd.WQQpcJWBpv/org.xquartz:0") does not match our id ("org.macosforge.xquartz"), unsetting.
X11.app: main(): argc=2
	argv[0] = /Applications/Utilities/XQuartz.app/Contents/MacOS/X11.bin
	argv[1] = --listenonly
Waiting for startup parameters via Mach IPC.
X11.app: No launchd socket handed off, unsetting DISPLAY
X11.app: do_start_x11_server(): argc=7
	argv[0] = /opt/X11/bin/Xquartz
	argv[1] = :0
	argv[2] = -nolisten
	argv[3] = tcp
	argv[4] = -iglx
	argv[5] = -auth
	argv[6] = /Users/aivilsstoss/.serverauth.4190
[139044.520] Xquartz starting:
[139044.520] X.Org X Server 1.18.4
[139044.520] Build Date: 20161025
[139044.523] x: 0, y: 0, w: 1920, h: 1178
[139044.539] (II) GLX: Initialized Core OpenGL GL provider for screen 0
[139044.607] X11.app: DarwinProcessFDAdditionQueue_thread: Sleeping to allow xinitrc to catchup.
[139044.624] (EE) Error loading keymap /tmp/server-0.xkm
[139044.624] (EE) XKB: Failed to load keymap. Loading default keymap instead.
[139046.238] noPseudoramiXExtension=0, pseudoramiXNumScreens=1
```

**Comment by tgorni** [comment]
Similarly to @aivils, /Application/Xquartz does not open on double click, but strangely it opens from command line. Once opened, I still cannot run xterm from terminal, but I can run xterm from the GUI of Xquartz (Applications-->Terminal), it gives a couple of warnings

Warning: locale not supported by Xlib, locale set to C
Fontconfig warning: ignoring UTF-8: not a valid region tag

but seems to work and the DISPLAY is set to :0

Why only this weird combination of GUI and command line is working?

**Comment by jeremyhu** [comment]
> If I run xterm from Xquartz (Applications -> Terminal), a window appears and the DISPLAY value is ":0".

That sounds like either your LaunchAgent isn't loaded for some reason, or something is overriding your DISPLAY.

What does `launchctl getenv DISPLAY` report?  Assuming it shows an appropriate value (eg: /private/tmp/...), then check your shell init scripts.  There are debugging tips for you at https://www.xquartz.org/FAQs.html

> X11.app: DISPLAY ("/private/tmp/com.apple.launchd.WQQpcJWBpv/org.xquartz:0") does not match our id ("org.macosforge.xquartz"), unsetting.

That means you are launching XQuartz 2.7.11 but have a 2.8.0 LaunchAgent loaded (ie: you didn't finish uninstalling 2.8.0 per the instructions on the FAQ ... you need to remove the LaunchAgent).

> /Application/Xquartz does not open on double click

You're probably getting a crash in 2.7.11 that can happen with the LaunchAgent mismatch which was fixed in 2.8.0 a few weeks ago

**Comment by jeremyhu** [comment]
So is the issue here just that you had the wrong $DISPLAY set?

Did you logout after moving from 2.7.11 to 2.8.0?  The installer is supposed to force you to logout in that case.

Did the old 2.7.x LaunchAgent not get removed (check `ls /Library/LaunchAgents/*startx*`)?  The post-install script is supposed to remove it.

Did your aqua session not teardown with logout?  Check `launchctl getenv DISPLAY`.  It should include 'org.xquartz' with 2.8.0 and not 'org.macosforge.xquartz'.

Is DISPLAY in your Terminal not matching what launchd is setting?  Check `echo $DISPLAY` and compare with `launchctl getenv DISPLAY`.

**Comment by aivils** [comment]
Yes there are two agents on my computer

```
bash-3.2$ ls -la /Library/LaunchAgents/*startx.plist
-rw-r--r--  1 root  wheel  715 Oct 26  2016 /Library/LaunchAgents/org.macosforge.xquartz.startx.plist
-rw-r--r--  1 root  wheel  693 Jan 30 02:50 /Library/LaunchAgents/org.xquartz.startx.plist
```

Since I want to keep 2.7.11 running, I will delete the latest startx agent that may be related to the 2.8.0 installation.

```
sudo rm /Library/LaunchAgents/org.xquartz.startx.plist
```

I logout/login and 2.7.11 xquartz starts working as befits.

**Comment by aivils** [comment]
I can't repeat it a second time. 2.8.0 was successfully installed. If, for some reason, there were two startx agents left in the system, then most likely the others also need to make sure that there is one real startx agent in the system.

**Comment by tgorni** [comment]
I'm still having the issue, and I've never installed 2.7. At present I have

`zsh ~ % ls -la /Library/LaunchAgents/*startx*`
`-rw-r--r--  1 root  wheel  693 Feb 27 06:37 /Library/LaunchAgents/org.xquartz.startx.plist`

`zsh ~ % launchctl getenv DISPLAY`
`/private/tmp/com.apple.launchd.eUbmQEkQNT/org.xquartz:0`

`zsh ~ % echo $DISPLAY`
`/private/tmp/com.apple.launchd.eUbmQEkQNT/org.xquartz:0`

And I incur in the problems stated above. As a workaround I put

`Xquartz &`
`export DISPLAY=':0'`

into my .zprofile, which kind of patches things up in a local session, but still yields slowdowns and strange behaviours in remote sessions. I'm considering to upgrade to Big Sur to see whether the sky is bluer there.

**Comment by jeremyhu** [comment]
@tgorni Your LaunchAgents and $DISPLAY look right.

You should not be starting XQuartz by running 'XQuartz' from your .zprofile.  That will cause a TON of problems for y ou as it will attempt to spawn a new X11 server for every login shell you start, and XQuartz.app itself starts login shells in order to get the login environment.  I would expect that doing something like that would fork-bomb your system and force you to reboot.

---

Please remove that from your .zprofile and then tell me what happens when you launch XQuartz.app?

What happens if you run 'xterm' from Terminal.app (again, without your hack in place)?

What do you see in  ~/Library/Logs/X11/org.xquartz.log that might shed some light on this?

**Comment by tgorni** [comment]
So Xquartz does not launch from GUI (bounces a couple of times and that's it), and `xterm` just don't work

```
zsh ~ % xterm

```
 but if I do

```
cd /Applications/Utilities
open Xquartz
```

then an `xterm` opens. Inside the `xterm`

```
zsh ~ % echo $DISPLAY                 
/private/tmp/com.apple.launchd.shTbF5tISc/org.xquartz:0
```

and everything seems to work more or less fine (even though a bit slow in remote). Now `xterm` works also from Terminal.app (actually I use iTerm), but with warning

```
zsh Utilities % xterm
Warning: locale not supported by Xlib, locale set to C
```

This is the whole  ~/Library/Logs/X11/org.xquartz.log while going through the steps above

```
X11.app: main(): argc=1
    argv[0] = /Applications/Utilities/XQuartz.app/Contents/MacOS/X11.bin
Waiting for startup parameters via Mach IPC.
X11.app: Listening on socket for fd handoff:  (5) /var/tmp/tmp.0.y1RDZk
X11.app: Thread created for handoff.  Returning success to tell caller to connect and push the fd.
X11.app Handing off fd to server thread via DarwinListenOnOpenFD(7)
X11.app: do_start_x11_server(): argc=7
    argv[0] = /opt/X11/bin/Xquartz
    argv[1] = :0
    argv[2] = -nolisten
    argv[3] = tcp
    argv[4] = -iglx
    argv[5] = -auth
    argv[6] = /Users/tommasogorni/.serverauth.2796
DarwinListenOnOpenFD: 7
[580294.690] Xquartz starting:
[580294.690] X.Org X Server 1.19.7
[580294.690] Build Date: 20210226
[580294.697] x: 0, y: 0, w: 1440, h: 878
[580294.712] (II) GLX: Initialized Core OpenGL GL provider for screen 0
[580294.840] X11.app: DarwinProcessFDAdditionQueue_thread: Sleeping to allow xinitrc to catchup.
[580294.856] (EE) Error loading keymap /tmp/server-0.xkm
[580294.856] (EE) XKB: Failed to load keymap. Loading default keymap instead.
[580295.016] noPseudoramiXExtension=0, pseudoramiXNumScreens=1
[580297.843] Calling ListenOnOpenFD() for new fd: 7
```

**Comment by jeremyhu** [comment]
Can you please get into your "bad" case?  Shutdown XQuartz, open up iTerm, and run 'xterm'.

When it's haning out and XQuartz.app is bouncing in the Dock, please run `sudo sysdiagnose -q XQuartz` and send the resulting tarball.  Please also send me ~/Library/Logs/X11.  The sysdiagnose might have some personal data in it (eg: list of installed apps, system logs, etc), so probably best to share it with me directly rather than on a shared github link.  If you want, you can send it to Apple via Feedback Assistant (eg: bugreport.apple.com) and point me at the FB#.

**Comment by tgorni** [comment]
I filed a feedback to Apple with the needed files, the name is

Xquartz not working on Catalina 10.15.7 (FB9040412)

Thanks a lot.

**Comment by jeremyhu** [comment]
In your report, you said,

> I installed Xquartz 2.8 on my MacBook Pro, but it does not launch from GUI (bounces a couple of times and that's it), and xterm or any other x app (xclock,...) are not opening from Terminal.app, but if I do
> 
> cd /Applications/Utilities
> open Xquartz
> 
> then an xterm opens. Inside the xterm

However, running 'open Xquartz' like that should result in an error:

> The file /Applications/Utilities/Xquartz does not exist.

What do you mean by "lauanch from GUI"?  Do you mean double clicking XQuartz.app?  That should do the same thing as `open -a XQuartz` or `open /Applications/Utilities/XQuartz.app`.  Do you mean running `xterm` from Terminal.app?

**Comment by jeremyhu** [comment]
In your spindump, I see:


```
Process:          xterm [3856]
UUID:             10043F7A-3F1B-33C5-BA3A-B16F32C5D144
Path:             /opt/X11/bin/xterm
Architecture:     x86_64
Parent:           zsh [3455]
Responsible:      iTerm2 [3452]
UID:              501
Footprint:        620 KB
Start time:       2021-03-12 11:05:44 +0100
End time:         2021-03-12 11:05:54 +0100
Num samples:      1000 (1-1000)

  Thread 0x6ab6    DispatchQueue 140735708292992    1000 samples (1-1000)    priority 31 (base 31)
  1000  start + 1 (libdyld.dylib + 109769) [0x7fff6f5c7cc9]
    1000  main + 2190 (xterm + 194082) [0x105bfb622]
      1000  xtermOpenApplication + 82 (xterm + 257934) [0x105c0af8e]
        1000  XtOpenApplication + 110 (libXt.6.dylib + 81279) [0x105e91d7f]
          1000  _XtAppInit + 192 (libXt.6.dylib + 45862) [0x105e89326]
            1000  XtOpenDisplay + 192 (libXt.6.dylib + 44667) [0x105e88e7b]
              1000  XOpenDisplay + 181 (libX11.6.dylib + 90999) [0x105ef0377]
                1000  _XConnectXCB + 198 (libX11.6.dylib + 147034) [0x105efde5a]
                  1000  xcb_connect_to_display_with_auth_info + 739 (libxcb.1.dylib + 22913) [0x10603f981]
                    1000  xcb_connect_to_fd + 510 (libxcb.1.dylib + 9622) [0x10603c596]
                      1000  poll + 10 (libsystem_kernel.dylib + 29654) [0x7fff6f70f3d6]
                       *1000  hndl_unix_scall64 + 22 (kernel + 786950) [0xffffff80002c0206]
                         *1000  unix_syscall64 + 647 (kernel + 7877447) [0xffffff8000983347]
                           *1000  poll_nocancel + 971 (kernel + 6955835) [0xffffff80008a233b]
                             *1000  kqueue_scan + 1782 (kernel + 6637846) [0xffffff8000854916]
                               *1000  thread_block_reason + 175 (kernel + 1285391) [0xffffff8000339d0f]
                                 *1000  ??? (kernel + 1291473) [0xffffff800033b4d1]
                                   *1000  machine_switch_context + 200 (kernel + 2361448) [0xffffff8000440868]

```

so it looks like you did take the sysdiagnose as I asked but just the text of the FB report is inconsistent.

Those frames indicate that xterm is trying to connect to the server.

The log in ~/Library/Logs/X11 indicates that the most recent invocations of the server launched and terminated cleanly, so it's not a crash.

**Comment by jeremyhu** [comment]
System log shows clean termination:

```
2021-03-12 07:58:47.271398+0100 0x313f     Info        0x0                  3106   0    X11.bin: (AE) [com.apple.appleevents:receive] RECEIVED:(aevt,quit) <private>
```

However this bit from /opt/X11/bin/Xquartz is interesting:

```
2021-03-12 11:06:56.149427+0100 0x74b5     Default     0x0                  4631   0    Xquartz: Xquartz: bootstrap_look_up(): Unknown service name
2021-03-12 11:06:56.799057+0100 0x7c00     Default     0x0                  5302   0    Xquartz: Xquartz: Unable to locate waiting server: org.xquartz.X11
```

**Comment by jeremyhu** [comment]
Do you have a ~/.xinitrc file or an ~/.xinitrc.d directory?  If so, can you move them aside and try again?  If that "fixes" the issue, I suggest digging into what about the init scripts is causing a problem.

**Comment by jeremyhu** [comment]
Given that this only fails in the LaunchAgent case, I wonder if the issue is that one of your init scripts fails is the current working directory isn't $HOME (#114).  Can you give 2.8.0_rc3 a try?

**Comment by tgorni** [comment]
That was my .zprofile indeed! In particular the problem was due to

```
source /opt/intel/oneapi/setvars.sh
```
which was setting environment variables for the intel compilers, never thought it could affect Xquartz!

Now everything is working properly, both locally and remotely, thanks a lot! (I didn't have any ~/.x* file in my $HOME.)

**Comment by jeremyhu** [comment]
I'd be curious if there's something we're doing wrong that is causing that issue to crop up or if it's just an unfortunate issue with that init script's assumptions.  Did our setting of $HOME in rc3 fix this?  Is there something we can better guard against?

**Comment by tgorni** [comment]
So I had not installed rc3 before, I simply moved aside my .zprofile.

Now I've just uninstalled rc2 and installed rc3, and the Intel `setvars.sh` breaks rc3 in the same way it breaks rc2. Don't know what I can look specifically at to help, `setvars.sh` was given with the `Intel oneAPI Toolkit`, maybe was naive on my side to source it in the .zprofile.
